### ISSUE TITLE
add a drafts folder

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/mail#24]
sometimes, players will be in the middle of writing a long email, when something requires they pay attention to other things in-game (e.g. getting attacked by a mob). the player currently has 2 choices: press "escape" and lose the email, or send it unfinished.

**Comment by S-S-X** [comment]
Also I think work should be saved as a draft when escape is pressed instead of dedicated button, if not sent then save unless explicitly discarded.
I do also believe that separate folder isn't really needed and might be better to not have one but just save what you were doing and continue from that saved state next time you open mail.

Yeah, my personal opinion about drafts folder is that it shouldn't have been invented in first place...

**Comment by fluxionary** [comment]
> Also I think work should be saved as a draft when escape is pressed instead of dedicated button

unfortunately that's a client issue; the client doesn't send anything other than `{quit = true}` when you press escape. the solution requires protocol updates at least, and possibly SSCSM.

**Comment by Athozus** [comment]
I just saw this issue now (skipped before), and I will add it after new storage system will be done (if it is successful), to get those tabs : Inbox - Sent messages - Drafts
