### ISSUE TITLE
Receivers lines too long (formspec issue)

### ISSUE THREAD

**Issue by Athozus** [mt-mods/mail#72]
There is a formspec issue when there are too much receivers : all receivers are displayed, then more info is hidden due to the size of the formspec.

* In sent view, it is easy, we just have to limit to 30 chars, like the subject column (with ...)
* In message view, it is more complicated, because it is presumed to show all the available info. Is there a way to do like an horizontal scrollbar, to allow long receiver list ?

**Comment by S-S-X** [comment]
Often this is done by displaying only first name or just part of the first name and then add number indicating how many more there is, like `player1 +28` would mean there's total 29 recipients.
To make use of all available space without having to think about how much space name needs you'd prob have to place number before names like maybe `30+ player1`.

In message view you could either make it scrollable or add button than opens text area with all recipients. Text area could be used elsewhere too (new message dialog, even on message lists for quick details).
Text area because that allows easily copying text and same form could later double as address editor if it seems good.
